export enum BlockType {
  AIR = 0,
  GRASS = 1,
  DIRT = 2,
  STONE = 3,
  COBBLESTONE = 4,
  OAK_WOOD = 5,
  OAK_PLANKS = 6,
  LEAVES = 7,
  SAND = 8,
  WATER = 9,
  GLASS = 10,
  BRICKS = 11,
  BOOKSHELF = 12,
  GLOWSTONE = 13,
  DIAMOND_ORE = 14,
  GOLD_ORE = 15,
  IRON_ORE = 16,
  COAL_ORE = 17,
  OBSIDIAN = 18,
  TNT = 19,
  CRAFTING_TABLE = 20,
  BEDROCK = 21,
  SNOW = 22,
  TORCH = 23,
  // Food & Survival Items
  APPLE = 24,
  BREAD = 25,
  RAW_BEEF = 26,
  COOKED_BEEF = 27,
  GOLDEN_APPLE = 28,
  WHEAT = 29,
  STICK = 30,
  // Tools & Weapons (Minecraft Tiers)
  WOODEN_PICKAXE = 31,
  STONE_PICKAXE = 32,
  IRON_PICKAXE = 33,
  DIAMOND_PICKAXE = 34,
  WOODEN_SWORD = 35,
  IRON_SWORD = 36,
  WOODEN_AXE = 37,
  IRON_AXE = 38,
  // New blocks & items requested by user
  DEEPSLATE = 39,
  DEEPSLATE_COAL_ORE = 40,
  DEEPSLATE_IRON_ORE = 41,
  DEEPSLATE_GOLD_ORE = 42,
  DEEPSLATE_DIAMOND_ORE = 43,
  COPPER_ORE = 44,
  DEEPSLATE_COPPER_ORE = 45,
  COPPER_INGOT = 46,
  COPPER_BLOCK = 47,
  COPPER_PICKAXE = 48,
  COPPER_SWORD = 49,
  DIAMOND_SWORD = 50,
  DIAMOND_CHESTPLATE = 51,
  IRON_CHESTPLATE = 52,
  STONE_BRICKS = 53,
  MOSSY_STONE_BRICKS = 54,
  CRACKED_STONE_BRICKS = 55,
  IRON_BARS = 56,
  END_PORTAL_FRAME = 57,
  END_PORTAL = 58,
  DIAMOND = 59,
  DIAMOND_HELMET = 60,
  DIAMOND_LEGGINGS = 61,
  DIAMOND_BOOTS = 62,
  IRON_HELMET = 63,
  IRON_LEGGINGS = 64,
  IRON_BOOTS = 65,
  SHIELD = 66,
  COAL = 67,
  RAW_IRON = 68,
  RAW_GOLD = 69,
  RAW_COPPER = 70,
  ICE = 71,
  SANDSTONE = 72,
  CACTUS = 73,
}

export type ToolType = 'pickaxe' | 'sword' | 'axe' | 'shovel' | 'none';
export type ArmorSlotType = 'helmet' | 'chestplate' | 'leggings' | 'boots' | 'shield';

export interface BlockDefinition {
  id: BlockType;
  name: string;
  nameTr: string;
  category: 'natural' | 'building' | 'minerals' | 'decorative' | 'food' | 'items' | 'tools';
  transparent?: boolean;
  opacity?: number;
  lightEmission?: number; // 0 to 1
  soundType: 'grass' | 'dirt' | 'stone' | 'wood' | 'sand' | 'glass';
  baseBreakTime: number; // base time in seconds to break with bare hands
  requiredToolTier?: number; // 0: Hand, 1: Wood, 2: Stone, 3: Iron, 4: Diamond
  requiredToolType?: ToolType; // 'pickaxe', 'axe', etc.
  iconColor: string;
  isFood?: boolean;
  hungerRestore?: number; // 1 to 20
  healthRestore?: number; // 1 to 20
  isPlaceable?: boolean;
  // Tool properties
  isTool?: boolean;
  toolType?: ToolType;
  toolTier?: number; // 1: Wood, 2: Stone, 3: Iron, 4: Diamond
  miningMultiplier?: number; // Speed multiplier on favored blocks
  attackDamage?: number;
  // Armor properties
  isArmor?: boolean;
  armorSlot?: ArmorSlotType;
  defensePoints?: number; // Visual shield/defense score
  damageReduction?: number; // Percent damage reduced (0.0 to 1.0)
}

export interface InventorySlot {
  type: BlockType;
  count: number;
}

export const BLOCK_DEFS: Record<BlockType, BlockDefinition> = {
  [BlockType.AIR]: {
    id: BlockType.AIR,
    name: 'Air',
    nameTr: 'Hava',
    category: 'natural',
    transparent: true,
    soundType: 'grass',
    baseBreakTime: 0,
    iconColor: 'transparent',
    isPlaceable: false,
  },
  [BlockType.GRASS]: {
    id: BlockType.GRASS,
    name: 'Grass Block',
    nameTr: 'Çimen Bloğu',
    category: 'natural',
    soundType: 'grass',
    baseBreakTime: 0.55,
    requiredToolTier: 0,
    iconColor: '#5b8e34',
    isPlaceable: true,
  },
  [BlockType.DIRT]: {
    id: BlockType.DIRT,
    name: 'Dirt',
    nameTr: 'Toprak',
    category: 'natural',
    soundType: 'dirt',
    baseBreakTime: 0.5,
    requiredToolTier: 0,
    iconColor: '#866043',
    isPlaceable: true,
  },
  [BlockType.STONE]: {
    id: BlockType.STONE,
    name: 'Stone',
    nameTr: 'Taş',
    category: 'natural',
    soundType: 'stone',
    baseBreakTime: 4.5, // 4.5s by hand, ~1.2s with wood pickaxe, ~0.65s with iron pickaxe
    requiredToolTier: 1, // Requires Wooden Pickaxe for cobblestone drop
    requiredToolType: 'pickaxe',
    iconColor: '#7d7d7d',
    isPlaceable: true,
  },
  [BlockType.COBBLESTONE]: {
    id: BlockType.COBBLESTONE,
    name: 'Cobblestone',
    nameTr: 'Kırıktaş',
    category: 'building',
    soundType: 'stone',
    baseBreakTime: 5.0,
    requiredToolTier: 1, // Requires Wooden Pickaxe
    requiredToolType: 'pickaxe',
    iconColor: '#636363',
    isPlaceable: true,
  },
  [BlockType.OAK_WOOD]: {
    id: BlockType.OAK_WOOD,
    name: 'Oak Wood',
    nameTr: 'Meşe Odunu',
    category: 'natural',
    soundType: 'wood',
    baseBreakTime: 2.2, // Faster with axe
    requiredToolTier: 0,
    iconColor: '#674a2b',
    isPlaceable: true,
  },
  [BlockType.OAK_PLANKS]: {
    id: BlockType.OAK_PLANKS,
    name: 'Oak Planks',
    nameTr: 'Meşe Tahta',
    category: 'building',
    soundType: 'wood',
    baseBreakTime: 1.8,
    requiredToolTier: 0,
    iconColor: '#a07849',
    isPlaceable: true,
  },
  [BlockType.LEAVES]: {
    id: BlockType.LEAVES,
    name: 'Oak Leaves',
    nameTr: 'Meşe Yaprakları',
    category: 'natural',
    transparent: true,
    opacity: 0.9,
    soundType: 'grass',
    baseBreakTime: 0.25,
    requiredToolTier: 0,
    iconColor: '#366c25',
    isPlaceable: true,
  },
  [BlockType.SAND]: {
    id: BlockType.SAND,
    name: 'Sand',
    nameTr: 'Kum',
    category: 'natural',
    soundType: 'sand',
    baseBreakTime: 0.5,
    requiredToolTier: 0,
    iconColor: '#d6c88f',
    isPlaceable: true,
  },
  [BlockType.WATER]: {
    id: BlockType.WATER,
    name: 'Water',
    nameTr: 'Su',
    category: 'natural',
    transparent: true,
    opacity: 0.65,
    soundType: 'sand',
    baseBreakTime: 0.1,
    iconColor: '#3f76e4',
    isPlaceable: true,
  },
  [BlockType.GLASS]: {
    id: BlockType.GLASS,
    name: 'Glass',
    nameTr: 'Cam',
    category: 'building',
    transparent: true,
    opacity: 0.45,
    soundType: 'glass',
    baseBreakTime: 0.35,
    requiredToolTier: 0,
    iconColor: '#e0f8ff',
    isPlaceable: true,
  },
  [BlockType.BRICKS]: {
    id: BlockType.BRICKS,
    name: 'Bricks',
    nameTr: 'Tuğla',
    category: 'building',
    soundType: 'stone',
    baseBreakTime: 4.0,
    requiredToolTier: 1,
    requiredToolType: 'pickaxe',
    iconColor: '#964836',
    isPlaceable: true,
  },
  [BlockType.BOOKSHELF]: {
    id: BlockType.BOOKSHELF,
    name: 'Bookshelf',
    nameTr: 'Kitaplık',
    category: 'decorative',
    soundType: 'wood',
    baseBreakTime: 1.5,
    requiredToolTier: 0,
    iconColor: '#8a6538',
    isPlaceable: true,
  },
  [BlockType.GLOWSTONE]: {
    id: BlockType.GLOWSTONE,
    name: 'Glowstone',
    nameTr: 'Işıktaşı',
    category: 'decorative',
    lightEmission: 1.0,
    soundType: 'glass',
    baseBreakTime: 0.45,
    requiredToolTier: 0,
    iconColor: '#f7d37a',
    isPlaceable: true,
  },
  [BlockType.COAL_ORE]: {
    id: BlockType.COAL_ORE,
    name: 'Coal Ore',
    nameTr: 'Kömür Cevheri',
    category: 'minerals',
    soundType: 'stone',
    baseBreakTime: 5.5,
    requiredToolTier: 1, // Requires Wooden Pickaxe
    requiredToolType: 'pickaxe',
    iconColor: '#303030',
    isPlaceable: true,
  },
  [BlockType.IRON_ORE]: {
    id: BlockType.IRON_ORE,
    name: 'Iron Ore',
    nameTr: 'Demir Cevheri',
    category: 'minerals',
    soundType: 'stone',
    baseBreakTime: 7.0,
    requiredToolTier: 2, // Requires Stone Pickaxe or better!
    requiredToolType: 'pickaxe',
    iconColor: '#d8af93',
    isPlaceable: true,
  },
  [BlockType.GOLD_ORE]: {
    id: BlockType.GOLD_ORE,
    name: 'Gold Ore',
    nameTr: 'Altın Cevheri',
    category: 'minerals',
    soundType: 'stone',
    baseBreakTime: 8.0,
    requiredToolTier: 3, // Requires Iron Pickaxe or better!
    requiredToolType: 'pickaxe',
    iconColor: '#fcee4b',
    isPlaceable: true,
  },
  [BlockType.DIAMOND_ORE]: {
    id: BlockType.DIAMOND_ORE,
    name: 'Diamond Ore',
    nameTr: 'Elmas Cevheri',
    category: 'minerals',
    soundType: 'stone',
    baseBreakTime: 10.0,
    requiredToolTier: 3, // Requires Iron Pickaxe or better! (as requested by user)
    requiredToolType: 'pickaxe',
    iconColor: '#4dedf4',
    isPlaceable: true,
  },
  [BlockType.OBSIDIAN]: {
    id: BlockType.OBSIDIAN,
    name: 'Obsidian',
    nameTr: 'Obsidyen',
    category: 'minerals',
    soundType: 'stone',
    baseBreakTime: 18.0,
    requiredToolTier: 4, // Requires Diamond Pickaxe!
    requiredToolType: 'pickaxe',
    iconColor: '#191326',
    isPlaceable: true,
  },
  [BlockType.TNT]: {
    id: BlockType.TNT,
    name: 'TNT',
    nameTr: 'Dinamit (TNT)',
    category: 'decorative',
    soundType: 'grass',
    baseBreakTime: 0.15,
    iconColor: '#db3725',
    isPlaceable: true,
  },
  [BlockType.CRAFTING_TABLE]: {
    id: BlockType.CRAFTING_TABLE,
    name: 'Crafting Table',
    nameTr: 'Çalışma Masası',
    category: 'decorative',
    soundType: 'wood',
    baseBreakTime: 1.5,
    iconColor: '#a6723e',
    isPlaceable: true,
  },
  [BlockType.BEDROCK]: {
    id: BlockType.BEDROCK,
    name: 'Bedrock',
    nameTr: 'Katman Kayası',
    category: 'natural',
    soundType: 'stone',
    baseBreakTime: 99999, // Unbreakable
    iconColor: '#333333',
    isPlaceable: true,
  },
  [BlockType.SNOW]: {
    id: BlockType.SNOW,
    name: 'Snow Block',
    nameTr: 'Kar Bloğu',
    category: 'natural',
    soundType: 'grass',
    baseBreakTime: 0.3,
    iconColor: '#eef3f7',
    isPlaceable: true,
  },
  [BlockType.TORCH]: {
    id: BlockType.TORCH,
    name: 'Torch',
    nameTr: 'Meşale',
    category: 'decorative',
    lightEmission: 0.9,
    soundType: 'wood',
    baseBreakTime: 0.1,
    iconColor: '#ffb300',
    isPlaceable: true,
  },
  // Foods
  [BlockType.APPLE]: {
    id: BlockType.APPLE,
    name: 'Red Apple',
    nameTr: 'Kırmızı Elma',
    category: 'food',
    soundType: 'grass',
    baseBreakTime: 0.1,
    iconColor: '#e12b2b',
    isFood: true,
    hungerRestore: 4,
    healthRestore: 2,
    isPlaceable: false,
  },
  [BlockType.BREAD]: {
    id: BlockType.BREAD,
    name: 'Bread',
    nameTr: 'Taze Ekmek',
    category: 'food',
    soundType: 'grass',
    baseBreakTime: 0.1,
    iconColor: '#c98e46',
    isFood: true,
    hungerRestore: 6,
    healthRestore: 3,
    isPlaceable: false,
  },
  [BlockType.RAW_BEEF]: {
    id: BlockType.RAW_BEEF,
    name: 'Raw Beef',
    nameTr: 'Çiğ Et',
    category: 'food',
    soundType: 'dirt',
    baseBreakTime: 0.1,
    iconColor: '#b03b3b',
    isFood: true,
    hungerRestore: 3,
    healthRestore: 1,
    isPlaceable: false,
  },
  [BlockType.COOKED_BEEF]: {
    id: BlockType.COOKED_BEEF,
    name: 'Cooked Steak',
    nameTr: 'Pişmiş Biftek',
    category: 'food',
    soundType: 'dirt',
    baseBreakTime: 0.1,
    iconColor: '#6e2b17',
    isFood: true,
    hungerRestore: 8,
    healthRestore: 4,
    isPlaceable: false,
  },
  [BlockType.GOLDEN_APPLE]: {
    id: BlockType.GOLDEN_APPLE,
    name: 'Golden Apple',
    nameTr: 'Altın Elma',
    category: 'food',
    soundType: 'glass',
    baseBreakTime: 0.1,
    iconColor: '#ffd700',
    isFood: true,
    hungerRestore: 20,
    healthRestore: 10,
    isPlaceable: false,
  },
  [BlockType.WHEAT]: {
    id: BlockType.WHEAT,
    name: 'Wheat',
    nameTr: 'Buğday',
    category: 'items',
    soundType: 'grass',
    baseBreakTime: 0.1,
    iconColor: '#c7b055',
    isPlaceable: false,
  },
  [BlockType.STICK]: {
    id: BlockType.STICK,
    name: 'Stick',
    nameTr: 'Çubuk',
    category: 'items',
    soundType: 'wood',
    baseBreakTime: 0.1,
    iconColor: '#704f2d',
    isPlaceable: false,
  },
  // Tools & Weapons (Pickaxes, Swords, Axes)
  [BlockType.WOODEN_PICKAXE]: {
    id: BlockType.WOODEN_PICKAXE,
    name: 'Wooden Pickaxe',
    nameTr: 'Tahta Kazma',
    category: 'tools',
    soundType: 'wood',
    baseBreakTime: 0.1,
    iconColor: '#9b7145',
    isTool: true,
    toolType: 'pickaxe',
    toolTier: 1, // Tier 1: Can mine Stone, Cobblestone, Coal
    miningMultiplier: 2.8,
    attackDamage: 2,
    isPlaceable: false,
  },
  [BlockType.STONE_PICKAXE]: {
    id: BlockType.STONE_PICKAXE,
    name: 'Stone Pickaxe',
    nameTr: 'Taş Kazma',
    category: 'tools',
    soundType: 'stone',
    baseBreakTime: 0.1,
    iconColor: '#888888',
    isTool: true,
    toolType: 'pickaxe',
    toolTier: 2, // Tier 2: Can mine Iron Ore!
    miningMultiplier: 4.8,
    attackDamage: 3,
    isPlaceable: false,
  },
  [BlockType.IRON_PICKAXE]: {
    id: BlockType.IRON_PICKAXE,
    name: 'Iron Pickaxe',
    nameTr: 'Demir Kazma',
    category: 'tools',
    soundType: 'stone',
    baseBreakTime: 0.1,
    iconColor: '#e0e0e0',
    isTool: true,
    toolType: 'pickaxe',
    toolTier: 3, // Tier 3: Can mine Gold Ore & Diamond Ore!
    miningMultiplier: 7.5,
    attackDamage: 4,
    isPlaceable: false,
  },
  [BlockType.DIAMOND_PICKAXE]: {
    id: BlockType.DIAMOND_PICKAXE,
    name: 'Diamond Pickaxe',
    nameTr: 'Elmas Kazma',
    category: 'tools',
    soundType: 'stone',
    baseBreakTime: 0.1,
    iconColor: '#4dedf4',
    isTool: true,
    toolType: 'pickaxe',
    toolTier: 4, // Tier 4: Can mine Obsidian!
    miningMultiplier: 12.0,
    attackDamage: 5,
    isPlaceable: false,
  },
  [BlockType.WOODEN_SWORD]: {
    id: BlockType.WOODEN_SWORD,
    name: 'Wooden Sword',
    nameTr: 'Tahta Kılıç',
    category: 'tools',
    soundType: 'wood',
    baseBreakTime: 0.1,
    iconColor: '#a07849',
    isTool: true,
    toolType: 'sword',
    toolTier: 1,
    miningMultiplier: 1.5,
    attackDamage: 4,
    isPlaceable: false,
  },
  [BlockType.IRON_SWORD]: {
    id: BlockType.IRON_SWORD,
    name: 'Iron Sword',
    nameTr: 'Demir Kılıç',
    category: 'tools',
    soundType: 'stone',
    baseBreakTime: 0.1,
    iconColor: '#d8af93',
    isTool: true,
    toolType: 'sword',
    toolTier: 3,
    miningMultiplier: 1.5,
    attackDamage: 7,
    isPlaceable: false,
  },
  [BlockType.WOODEN_AXE]: {
    id: BlockType.WOODEN_AXE,
    name: 'Wooden Axe',
    nameTr: 'Tahta Balta',
    category: 'tools',
    soundType: 'wood',
    baseBreakTime: 0.1,
    iconColor: '#8a6538',
    isTool: true,
    toolType: 'axe',
    toolTier: 1,
    miningMultiplier: 3.0,
    attackDamage: 3,
    isPlaceable: false,
  },
  [BlockType.IRON_AXE]: {
    id: BlockType.IRON_AXE,
    name: 'Iron Axe',
    nameTr: 'Demir Balta',
    category: 'tools',
    soundType: 'stone',
    baseBreakTime: 0.1,
    iconColor: '#d0d0d0',
    isTool: true,
    toolType: 'axe',
    toolTier: 3,
    miningMultiplier: 6.5,
    attackDamage: 5,
    isPlaceable: false,
  },
  // Deepslate & New Ores
  [BlockType.DEEPSLATE]: {
    id: BlockType.DEEPSLATE,
    name: 'Deepslate',
    nameTr: 'Derin Kaynak Taşı',
    category: 'natural',
    soundType: 'stone',
    baseBreakTime: 6.0,
    requiredToolTier: 1, // Requires Wooden Pickaxe or better
    requiredToolType: 'pickaxe',
    iconColor: '#30303b',
    isPlaceable: true,
  },
  [BlockType.DEEPSLATE_COAL_ORE]: {
    id: BlockType.DEEPSLATE_COAL_ORE,
    name: 'Deepslate Coal Ore',
    nameTr: 'Derin Kömür Cevheri',
    category: 'minerals',
    soundType: 'stone',
    baseBreakTime: 6.5,
    requiredToolTier: 1,
    requiredToolType: 'pickaxe',
    iconColor: '#2b2b32',
    isPlaceable: true,
  },
  [BlockType.DEEPSLATE_IRON_ORE]: {
    id: BlockType.DEEPSLATE_IRON_ORE,
    name: 'Deepslate Iron Ore',
    nameTr: 'Derin Demir Cevheri',
    category: 'minerals',
    soundType: 'stone',
    baseBreakTime: 8.0,
    requiredToolTier: 2, // Stone pickaxe
    requiredToolType: 'pickaxe',
    iconColor: '#936a53',
    isPlaceable: true,
  },
  [BlockType.DEEPSLATE_GOLD_ORE]: {
    id: BlockType.DEEPSLATE_GOLD_ORE,
    name: 'Deepslate Gold Ore',
    nameTr: 'Derin Altın Cevheri',
    category: 'minerals',
    soundType: 'stone',
    baseBreakTime: 9.0,
    requiredToolTier: 3, // Iron pickaxe
    requiredToolType: 'pickaxe',
    iconColor: '#d4af37',
    isPlaceable: true,
  },
  [BlockType.DEEPSLATE_DIAMOND_ORE]: {
    id: BlockType.DEEPSLATE_DIAMOND_ORE,
    name: 'Deepslate Diamond Ore',
    nameTr: 'Derin Elmas Cevheri',
    category: 'minerals',
    soundType: 'stone',
    baseBreakTime: 12.0,
    requiredToolTier: 3, // Iron pickaxe
    requiredToolType: 'pickaxe',
    iconColor: '#2fd5e3',
    isPlaceable: true,
  },
  [BlockType.COPPER_ORE]: {
    id: BlockType.COPPER_ORE,
    name: 'Copper Ore',
    nameTr: 'Bakır Cevheri',
    category: 'minerals',
    soundType: 'stone',
    baseBreakTime: 5.5,
    requiredToolTier: 1, // Wooden pickaxe
    requiredToolType: 'pickaxe',
    iconColor: '#d06e42',
    isPlaceable: true,
  },
  [BlockType.DEEPSLATE_COPPER_ORE]: {
    id: BlockType.DEEPSLATE_COPPER_ORE,
    name: 'Deepslate Copper Ore',
    nameTr: 'Derin Bakır Cevheri',
    category: 'minerals',
    soundType: 'stone',
    baseBreakTime: 7.5,
    requiredToolTier: 2, // Stone pickaxe
    requiredToolType: 'pickaxe',
    iconColor: '#bc5b32',
    isPlaceable: true,
  },
  [BlockType.COPPER_INGOT]: {
    id: BlockType.COPPER_INGOT,
    name: 'Copper Ingot',
    nameTr: 'Bakır Külçesi',
    category: 'items',
    soundType: 'stone',
    baseBreakTime: 0.1,
    iconColor: '#c86438',
    isPlaceable: false,
  },
  [BlockType.COPPER_BLOCK]: {
    id: BlockType.COPPER_BLOCK,
    name: 'Block of Copper',
    nameTr: 'Bakır Bloğu',
    category: 'building',
    soundType: 'stone',
    baseBreakTime: 4.5,
    requiredToolTier: 1,
    requiredToolType: 'pickaxe',
    iconColor: '#c86438',
    isPlaceable: true,
  },
  [BlockType.COPPER_PICKAXE]: {
    id: BlockType.COPPER_PICKAXE,
    name: 'Copper Pickaxe',
    nameTr: 'Bakır Kazma',
    category: 'tools',
    soundType: 'stone',
    baseBreakTime: 0.1,
    iconColor: '#c86438',
    isTool: true,
    toolType: 'pickaxe',
    toolTier: 2,
    miningMultiplier: 4.0,
    attackDamage: 3,
    isPlaceable: false,
  },
  [BlockType.COPPER_SWORD]: {
    id: BlockType.COPPER_SWORD,
    name: 'Copper Sword',
    nameTr: 'Bakır Kılıç',
    category: 'tools',
    soundType: 'stone',
    baseBreakTime: 0.1,
    iconColor: '#c86438',
    isTool: true,
    toolType: 'sword',
    toolTier: 2,
    miningMultiplier: 1.5,
    attackDamage: 5,
    isPlaceable: false,
  },
  [BlockType.DIAMOND_SWORD]: {
    id: BlockType.DIAMOND_SWORD,
    name: 'Diamond Sword',
    nameTr: 'Elmas Kılıç',
    category: 'tools',
    soundType: 'stone',
    baseBreakTime: 0.1,
    iconColor: '#4dedf4',
    isTool: true,
    toolType: 'sword',
    toolTier: 4,
    miningMultiplier: 2.0,
    attackDamage: 9, // Highest damage for boss fight!
    isPlaceable: false,
  },
  [BlockType.DIAMOND_CHESTPLATE]: {
    id: BlockType.DIAMOND_CHESTPLATE,
    name: 'Diamond Chestplate',
    nameTr: 'Elmas Zırh',
    category: 'tools',
    soundType: 'stone',
    baseBreakTime: 0.1,
    iconColor: '#4dedf4',
    isTool: true,
    isArmor: true,
    armorSlot: 'chestplate',
    defensePoints: 8,
    damageReduction: 0.45, // 45% damage reduction from chestplate alone
    isPlaceable: false,
  },
  [BlockType.IRON_CHESTPLATE]: {
    id: BlockType.IRON_CHESTPLATE,
    name: 'Iron Chestplate',
    nameTr: 'Demir Zırh',
    category: 'tools',
    soundType: 'stone',
    baseBreakTime: 0.1,
    iconColor: '#d8af93',
    isTool: true,
    isArmor: true,
    armorSlot: 'chestplate',
    defensePoints: 6,
    damageReduction: 0.30, // 30% damage reduction from iron chestplate
    isPlaceable: false,
  },
  [BlockType.DIAMOND_HELMET]: {
    id: BlockType.DIAMOND_HELMET,
    name: 'Diamond Helmet',
    nameTr: 'Elmas Kask',
    category: 'tools',
    soundType: 'stone',
    baseBreakTime: 0.1,
    iconColor: '#4dedf4',
    isTool: true,
    isArmor: true,
    armorSlot: 'helmet',
    defensePoints: 3,
    damageReduction: 0.18,
    isPlaceable: false,
  },
  [BlockType.DIAMOND_LEGGINGS]: {
    id: BlockType.DIAMOND_LEGGINGS,
    name: 'Diamond Leggings',
    nameTr: 'Elmas Pantolon',
    category: 'tools',
    soundType: 'stone',
    baseBreakTime: 0.1,
    iconColor: '#4dedf4',
    isTool: true,
    isArmor: true,
    armorSlot: 'leggings',
    defensePoints: 6,
    damageReduction: 0.25,
    isPlaceable: false,
  },
  [BlockType.DIAMOND_BOOTS]: {
    id: BlockType.DIAMOND_BOOTS,
    name: 'Diamond Boots',
    nameTr: 'Elmas Botlar',
    category: 'tools',
    soundType: 'stone',
    baseBreakTime: 0.1,
    iconColor: '#4dedf4',
    isTool: true,
    isArmor: true,
    armorSlot: 'boots',
    defensePoints: 3,
    damageReduction: 0.12,
    isPlaceable: false,
  },
  [BlockType.IRON_HELMET]: {
    id: BlockType.IRON_HELMET,
    name: 'Iron Helmet',
    nameTr: 'Demir Kask',
    category: 'tools',
    soundType: 'stone',
    baseBreakTime: 0.1,
    iconColor: '#d8af93',
    isTool: true,
    isArmor: true,
    armorSlot: 'helmet',
    defensePoints: 2,
    damageReduction: 0.12,
    isPlaceable: false,
  },
  [BlockType.IRON_LEGGINGS]: {
    id: BlockType.IRON_LEGGINGS,
    name: 'Iron Leggings',
    nameTr: 'Demir Pantolon',
    category: 'tools',
    soundType: 'stone',
    baseBreakTime: 0.1,
    iconColor: '#d8af93',
    isTool: true,
    isArmor: true,
    armorSlot: 'leggings',
    defensePoints: 5,
    damageReduction: 0.18,
    isPlaceable: false,
  },
  [BlockType.IRON_BOOTS]: {
    id: BlockType.IRON_BOOTS,
    name: 'Iron Boots',
    nameTr: 'Demir Botlar',
    category: 'tools',
    soundType: 'stone',
    baseBreakTime: 0.1,
    iconColor: '#d8af93',
    isTool: true,
    isArmor: true,
    armorSlot: 'boots',
    defensePoints: 2,
    damageReduction: 0.10,
    isPlaceable: false,
  },
  [BlockType.SHIELD]: {
    id: BlockType.SHIELD,
    name: 'Shield',
    nameTr: 'Kalkan',
    category: 'tools',
    soundType: 'wood',
    baseBreakTime: 0.1,
    iconColor: '#9b7145',
    isTool: true,
    isArmor: true,
    armorSlot: 'shield',
    defensePoints: 4,
    damageReduction: 0.25,
    isPlaceable: false,
  },
  [BlockType.DIAMOND]: {
    id: BlockType.DIAMOND,
    name: 'Diamond',
    nameTr: 'Elmas',
    category: 'items',
    soundType: 'stone',
    baseBreakTime: 0.1,
    iconColor: '#4dedf4',
    isPlaceable: false,
  },
  [BlockType.COAL]: {
    id: BlockType.COAL,
    name: 'Coal',
    nameTr: 'Kömür',
    category: 'items',
    soundType: 'stone',
    baseBreakTime: 0.1,
    iconColor: '#2b2b2b',
    isPlaceable: false,
  },
  [BlockType.RAW_IRON]: {
    id: BlockType.RAW_IRON,
    name: 'Raw Iron',
    nameTr: 'Ham Demir',
    category: 'items',
    soundType: 'stone',
    baseBreakTime: 0.1,
    iconColor: '#d8af93',
    isPlaceable: false,
  },
  [BlockType.RAW_GOLD]: {
    id: BlockType.RAW_GOLD,
    name: 'Raw Gold',
    nameTr: 'Ham Altın',
    category: 'items',
    soundType: 'stone',
    baseBreakTime: 0.1,
    iconColor: '#fcee4b',
    isPlaceable: false,
  },
  [BlockType.RAW_COPPER]: {
    id: BlockType.RAW_COPPER,
    name: 'Raw Copper',
    nameTr: 'Ham Bakır',
    category: 'items',
    soundType: 'stone',
    baseBreakTime: 0.1,
    iconColor: '#c86438',
    isPlaceable: false,
  },
  // Stronghold & Portal Blocks
  [BlockType.STONE_BRICKS]: {
    id: BlockType.STONE_BRICKS,
    name: 'Stone Bricks',
    nameTr: 'Taş Tuğla',
    category: 'building',
    soundType: 'stone',
    baseBreakTime: 4.0,
    requiredToolTier: 1,
    requiredToolType: 'pickaxe',
    iconColor: '#6f6f6f',
    isPlaceable: true,
  },
  [BlockType.MOSSY_STONE_BRICKS]: {
    id: BlockType.MOSSY_STONE_BRICKS,
    name: 'Mossy Stone Bricks',
    nameTr: 'Yosunlu Taş Tuğla',
    category: 'building',
    soundType: 'stone',
    baseBreakTime: 4.0,
    requiredToolTier: 1,
    requiredToolType: 'pickaxe',
    iconColor: '#5c6d54',
    isPlaceable: true,
  },
  [BlockType.CRACKED_STONE_BRICKS]: {
    id: BlockType.CRACKED_STONE_BRICKS,
    name: 'Cracked Stone Bricks',
    nameTr: 'Çatlak Taş Tuğla',
    category: 'building',
    soundType: 'stone',
    baseBreakTime: 3.5,
    requiredToolTier: 1,
    requiredToolType: 'pickaxe',
    iconColor: '#5a5a5a',
    isPlaceable: true,
  },
  [BlockType.IRON_BARS]: {
    id: BlockType.IRON_BARS,
    name: 'Iron Bars',
    nameTr: 'Demir Parmaklık',
    category: 'building',
    transparent: true,
    soundType: 'stone',
    baseBreakTime: 3.0,
    requiredToolTier: 1,
    requiredToolType: 'pickaxe',
    iconColor: '#8a8a9a',
    isPlaceable: true,
  },
  [BlockType.END_PORTAL_FRAME]: {
    id: BlockType.END_PORTAL_FRAME,
    name: 'End Portal Frame',
    nameTr: 'Portal Çerçevesi',
    category: 'minerals',
    soundType: 'stone',
    baseBreakTime: 99999, // indestructible or very tough
    iconColor: '#3d6350',
    isPlaceable: true,
  },
  [BlockType.END_PORTAL]: {
    id: BlockType.END_PORTAL,
    name: 'End Portal',
    nameTr: 'Aktif Portal',
    category: 'minerals',
    transparent: true,
    opacity: 0.85,
    lightEmission: 1.0,
    soundType: 'glass',
    baseBreakTime: 99999,
    iconColor: '#0b0416',
    isPlaceable: false,
  },
  [BlockType.ICE]: {
    id: BlockType.ICE,
    name: 'Ice',
    nameTr: 'Buz',
    category: 'natural',
    soundType: 'glass',
    transparent: true,
    baseBreakTime: 0.4,
    iconColor: '#8bd0eb',
    isPlaceable: true,
  },
  [BlockType.SANDSTONE]: {
    id: BlockType.SANDSTONE,
    name: 'Sandstone',
    nameTr: 'Kumtaşı',
    category: 'building',
    soundType: 'stone',
    baseBreakTime: 0.8,
    iconColor: '#ded29a',
    isPlaceable: true,
  },
  [BlockType.CACTUS]: {
    id: BlockType.CACTUS,
    name: 'Cactus',
    nameTr: 'Kaktüs',
    category: 'natural',
    soundType: 'grass',
    baseBreakTime: 0.3,
    iconColor: '#4f8c2b',
    isPlaceable: true,
  },
};

// Crafting Recipes definition
export interface CraftingRecipe {
  id: string;
  nameTr: string;
  inputs: { type: BlockType; count: number }[];
  output: { type: BlockType; count: number };
  description: string;
  gridType?: '2x2' | '3x3'; // 2x2 = inventory craftable, 3x3 = requires Crafting Table!
}

export const CRAFTING_RECIPES: CraftingRecipe[] = [
  // --- 2x2 Player Inventory Crafting (No table required) ---
  {
    id: 'wood_to_planks',
    nameTr: 'Meşe Tahta (4x)',
    inputs: [{ type: BlockType.OAK_WOOD, count: 1 }],
    output: { type: BlockType.OAK_PLANKS, count: 4 },
    description: '1 Odun -> 4 Tahta',
    gridType: '2x2',
  },
  {
    id: 'planks_to_sticks',
    nameTr: 'Çubuk (4x)',
    inputs: [{ type: BlockType.OAK_PLANKS, count: 2 }],
    output: { type: BlockType.STICK, count: 4 },
    description: '2 Tahta -> 4 Çubuk',
    gridType: '2x2',
  },
  {
    id: 'planks_to_crafting_table',
    nameTr: 'Çalışma Masası',
    inputs: [{ type: BlockType.OAK_PLANKS, count: 4 }],
    output: { type: BlockType.CRAFTING_TABLE, count: 1 },
    description: '4 Tahta -> 1 Çalışma Masası',
    gridType: '2x2',
  },
  {
    id: 'torch_craft',
    nameTr: 'Meşale (4x)',
    inputs: [
      { type: BlockType.STICK, count: 1 },
      { type: BlockType.COAL_ORE, count: 1 },
    ],
    output: { type: BlockType.TORCH, count: 4 },
    description: '1 Çubuk + 1 Kömür -> 4 Meşale',
    gridType: '2x2',
  },
  {
    id: 'wheat_to_bread',
    nameTr: 'Taze Ekmek',
    inputs: [{ type: BlockType.WHEAT, count: 3 }],
    output: { type: BlockType.BREAD, count: 1 },
    description: '3 Buğday -> 1 Ekmek (+6 Açlık)',
    gridType: '2x2',
  },
  {
    id: 'cook_beef',
    nameTr: 'Et Pişir (Pişmiş Biftek)',
    inputs: [
      { type: BlockType.RAW_BEEF, count: 1 },
      { type: BlockType.COAL_ORE, count: 1 },
    ],
    output: { type: BlockType.COOKED_BEEF, count: 1 },
    description: 'Çiğ Et + Kömür -> Pişmiş Biftek (+8 Açlık)',
    gridType: '2x2',
  },
  {
    id: 'smelt_copper',
    nameTr: 'Bakır Erit (Bakır Külçesi)',
    inputs: [
      { type: BlockType.COPPER_ORE, count: 1 },
      { type: BlockType.COAL_ORE, count: 1 },
    ],
    output: { type: BlockType.COPPER_INGOT, count: 1 },
    description: '1 Bakır Cevheri + Kömür -> 1 Bakır Külçesi',
    gridType: '2x2',
  },
  {
    id: 'copper_block_craft',
    nameTr: 'Bakır Bloğu',
    inputs: [{ type: BlockType.COPPER_INGOT, count: 4 }],
    output: { type: BlockType.COPPER_BLOCK, count: 1 },
    description: '4 Bakır Külçesi -> 1 Bakır Bloğu',
    gridType: '2x2',
  },
  {
    id: 'deepslate_bricks_craft',
    nameTr: 'Taş Tuğla (4x)',
    inputs: [{ type: BlockType.DEEPSLATE, count: 4 }],
    output: { type: BlockType.STONE_BRICKS, count: 4 },
    description: '4 Derin Kaynak Taşı -> 4 Taş Tuğla',
    gridType: '2x2',
  },

  // --- 3x3 Advanced Crafting (Çalışma Masası Zorunlu!) ---
  {
    id: 'craft_wooden_pickaxe',
    nameTr: 'Tahta Kazma',
    inputs: [
      { type: BlockType.OAK_PLANKS, count: 3 },
      { type: BlockType.STICK, count: 2 },
    ],
    output: { type: BlockType.WOODEN_PICKAXE, count: 1 },
    description: '3 Tahta + 2 Çubuk (Çalışma Masası)',
    gridType: '3x3',
  },
  {
    id: 'craft_stone_pickaxe',
    nameTr: 'Taş Kazma',
    inputs: [
      { type: BlockType.COBBLESTONE, count: 3 },
      { type: BlockType.STICK, count: 2 },
    ],
    output: { type: BlockType.STONE_PICKAXE, count: 1 },
    description: '3 Kırıktaş + 2 Çubuk -> Demir kazar!',
    gridType: '3x3',
  },
  {
    id: 'craft_copper_pickaxe',
    nameTr: 'Bakır Kazma',
    inputs: [
      { type: BlockType.COPPER_INGOT, count: 3 },
      { type: BlockType.STICK, count: 2 },
    ],
    output: { type: BlockType.COPPER_PICKAXE, count: 1 },
    description: '3 Bakır + 2 Çubuk -> Hızlı kazı!',
    gridType: '3x3',
  },
  {
    id: 'craft_iron_pickaxe',
    nameTr: 'Demir Kazma',
    inputs: [
      { type: BlockType.IRON_ORE, count: 3 },
      { type: BlockType.STICK, count: 2 },
    ],
    output: { type: BlockType.IRON_PICKAXE, count: 1 },
    description: '3 Demir + 2 Çubuk -> Altın ve Elmas kazar!',
    gridType: '3x3',
  },
  {
    id: 'craft_diamond_pickaxe',
    nameTr: 'Elmas Kazma',
    inputs: [
      { type: BlockType.DIAMOND_ORE, count: 3 },
      { type: BlockType.STICK, count: 2 },
    ],
    output: { type: BlockType.DIAMOND_PICKAXE, count: 1 },
    description: '3 Elmas + 2 Çubuk -> Obsidyen ve her şeyi kazar!',
    gridType: '3x3',
  },
  // Swords & Weapons
  {
    id: 'craft_wooden_sword',
    nameTr: 'Tahta Kılıç',
    inputs: [
      { type: BlockType.OAK_PLANKS, count: 2 },
      { type: BlockType.STICK, count: 1 },
    ],
    output: { type: BlockType.WOODEN_SWORD, count: 1 },
    description: '2 Tahta + 1 Çubuk -> 4 Hasar',
    gridType: '3x3',
  },
  {
    id: 'craft_copper_sword',
    nameTr: 'Bakır Kılıç',
    inputs: [
      { type: BlockType.COPPER_INGOT, count: 2 },
      { type: BlockType.STICK, count: 1 },
    ],
    output: { type: BlockType.COPPER_SWORD, count: 1 },
    description: '2 Bakır + 1 Çubuk -> 5 Hasar',
    gridType: '3x3',
  },
  {
    id: 'craft_iron_sword',
    nameTr: 'Demir Kılıç',
    inputs: [
      { type: BlockType.IRON_ORE, count: 2 },
      { type: BlockType.STICK, count: 1 },
    ],
    output: { type: BlockType.IRON_SWORD, count: 1 },
    description: '2 Demir + 1 Çubuk -> 7 Hasar',
    gridType: '3x3',
  },
  {
    id: 'craft_diamond_sword',
    nameTr: 'Elmas Kılıç',
    inputs: [
      { type: BlockType.DIAMOND_ORE, count: 2 },
      { type: BlockType.STICK, count: 1 },
    ],
    output: { type: BlockType.DIAMOND_SWORD, count: 1 },
    description: '2 Elmas + 1 Çubuk -> 9 Hasar (Canavara Karşı Güçlü!)',
    gridType: '3x3',
  },
  // Armor
  {
    id: 'craft_iron_helmet',
    nameTr: 'Demir Kask',
    inputs: [{ type: BlockType.IRON_ORE, count: 5 }],
    output: { type: BlockType.IRON_HELMET, count: 1 },
    description: '5 Demir -> Baş Koruması',
    gridType: '3x3',
  },
  {
    id: 'craft_iron_chestplate',
    nameTr: 'Demir Zırh',
    inputs: [{ type: BlockType.IRON_ORE, count: 8 }],
    output: { type: BlockType.IRON_CHESTPLATE, count: 1 },
    description: '8 Demir -> Yüksek Gövde Savunması (%30)',
    gridType: '3x3',
  },
  {
    id: 'craft_iron_leggings',
    nameTr: 'Demir Pantolon',
    inputs: [{ type: BlockType.IRON_ORE, count: 7 }],
    output: { type: BlockType.IRON_LEGGINGS, count: 1 },
    description: '7 Demir -> Bacak Koruması',
    gridType: '3x3',
  },
  {
    id: 'craft_iron_boots',
    nameTr: 'Demir Botlar',
    inputs: [{ type: BlockType.IRON_ORE, count: 4 }],
    output: { type: BlockType.IRON_BOOTS, count: 1 },
    description: '4 Demir -> Ayak Koruması',
    gridType: '3x3',
  },
  {
    id: 'craft_diamond_helmet',
    nameTr: 'Elmas Kask',
    inputs: [{ type: BlockType.DIAMOND, count: 5 }],
    output: { type: BlockType.DIAMOND_HELMET, count: 1 },
    description: '5 Elmas -> Maksimum Baş Koruması',
    gridType: '3x3',
  },
  {
    id: 'craft_diamond_chestplate',
    nameTr: 'Elmas Zırh',
    inputs: [{ type: BlockType.DIAMOND, count: 8 }],
    output: { type: BlockType.DIAMOND_CHESTPLATE, count: 1 },
    description: '8 Elmas -> Maksimum Gövde Savunması (%45)',
    gridType: '3x3',
  },
  {
    id: 'craft_diamond_leggings',
    nameTr: 'Elmas Pantolon',
    inputs: [{ type: BlockType.DIAMOND, count: 7 }],
    output: { type: BlockType.DIAMOND_LEGGINGS, count: 1 },
    description: '7 Elmas -> Maksimum Bacak Koruması',
    gridType: '3x3',
  },
  {
    id: 'craft_diamond_boots',
    nameTr: 'Elmas Botlar',
    inputs: [{ type: BlockType.DIAMOND, count: 4 }],
    output: { type: BlockType.DIAMOND_BOOTS, count: 1 },
    description: '4 Elmas -> Maksimum Ayak Koruması',
    gridType: '3x3',
  },
  {
    id: 'craft_shield',
    nameTr: 'Kalkan',
    inputs: [
      { type: BlockType.OAK_PLANKS, count: 6 },
      { type: BlockType.IRON_ORE, count: 1 },
    ],
    output: { type: BlockType.SHIELD, count: 1 },
    description: '6 Tahta + 1 Demir -> Sol Ele Takılır, Savunma Sağlar',
    gridType: '3x3',
  },
  {
    id: 'craft_diamond_cut',
    nameTr: 'Elmas Cevherini Parçala',
    inputs: [{ type: BlockType.DIAMOND_ORE, count: 1 }],
    output: { type: BlockType.DIAMOND, count: 1 },
    description: '1 Elmas Cevheri -> 1 Saf Elmas Gem',
    gridType: '2x2',
  },
  // Axes
  {
    id: 'craft_wooden_axe',
    nameTr: 'Tahta Balta',
    inputs: [
      { type: BlockType.OAK_PLANKS, count: 3 },
      { type: BlockType.STICK, count: 2 },
    ],
    output: { type: BlockType.WOODEN_AXE, count: 1 },
    description: '3 Tahta + 2 Çubuk -> Ağaçları hızla keser',
    gridType: '3x3',
  },
  {
    id: 'craft_iron_axe',
    nameTr: 'Demir Balta',
    inputs: [
      { type: BlockType.IRON_ORE, count: 3 },
      { type: BlockType.STICK, count: 2 },
    ],
    output: { type: BlockType.IRON_AXE, count: 1 },
    description: '3 Demir + 2 Çubuk -> Odunları çok hızlı keser',
    gridType: '3x3',
  },
  {
    id: 'golden_apple_craft',
    nameTr: 'Büyülü Altın Elma',
    inputs: [
      { type: BlockType.APPLE, count: 1 },
      { type: BlockType.GOLD_ORE, count: 4 },
    ],
    output: { type: BlockType.GOLDEN_APPLE, count: 1 },
    description: '1 Elma + 4 Altın -> Tam Can & Açlık',
    gridType: '3x3',
  },
];

// Initial starter hotbar items:
// User requested: "Oyun gerçekteki gibi olsun hiçbir eşya verilmeden başlayalım"
// In Survival: Start completely empty! (9 empty slots)
export const DEFAULT_SURVIVAL_HOTBAR: InventorySlot[] = [
  { type: BlockType.AIR, count: 0 },
  { type: BlockType.AIR, count: 0 },
  { type: BlockType.AIR, count: 0 },
  { type: BlockType.AIR, count: 0 },
  { type: BlockType.AIR, count: 0 },
  { type: BlockType.AIR, count: 0 },
  { type: BlockType.AIR, count: 0 },
  { type: BlockType.AIR, count: 0 },
  { type: BlockType.AIR, count: 0 },
];

export const DEFAULT_CREATIVE_HOTBAR: InventorySlot[] = [
  { type: BlockType.DIAMOND_PICKAXE, count: 1 },
  { type: BlockType.DIAMOND_SWORD, count: 1 },
  { type: BlockType.GRASS, count: 64 },
  { type: BlockType.DIRT, count: 64 },
  { type: BlockType.STONE, count: 64 },
  { type: BlockType.OAK_PLANKS, count: 64 },
  { type: BlockType.COBBLESTONE, count: 64 },
  { type: BlockType.DEEPSLATE, count: 64 },
  { type: BlockType.DIAMOND_ORE, count: 64 },
];

export const DEFAULT_HOTBAR: BlockType[] = [
  BlockType.AIR,
  BlockType.AIR,
  BlockType.AIR,
  BlockType.AIR,
  BlockType.AIR,
  BlockType.AIR,
  BlockType.AIR,
  BlockType.AIR,
  BlockType.AIR,
];

// Total inventory slots = 9 hotbar + 27 backpack = 36 slots
export const INVENTORY_SIZE = 36;
export const HOTBAR_SIZE = 9;

// World generation constants - EXPANDED WORLD AREA (128 x 128) with 16x16 Chunking
export const WORLD_SIZE_X = 128;
export const WORLD_SIZE_Z = 128;
export const CHUNK_SIZE = 16;
export const WORLD_HEIGHT = 46;
export const WATER_LEVEL = 10;

// Physics constants
export const GRAVITY = 22;
export const JUMP_VELOCITY = 8.5;
export const WALK_SPEED = 5.2;
export const SPRINT_SPEED = 8.0;
export const FLY_SPEED = 9.5;
// Radius 0.26 ensures effortless vertical entry into 1x1 shafts when digging down!
export const PLAYER_RADIUS = 0.26;
export const PLAYER_HEIGHT = 1.75;
export const EYE_HEIGHT = 1.62;
export const CROUCH_HEIGHT = 1.30;
export const CROUCH_EYE_HEIGHT = 1.15;
export const SNEAK_SPEED = 2.6;
